name: PHP Tiap 4 Jam Lewat 1 Menit UTC

on:
  schedule:
    - cron: '1 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Jalankan script.php
        run: php script.php
