name: PHP Tiap 2 Jam Lewat 2 Menit WIB

on:
  schedule:
    - cron: '2 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Jalankan script.php
        run: php script.php
